name: Pull Request Workflow

on:  pull_request

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit Tests
        run: ./gradlew test

  check:
    name: Lint, Ktlint and Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Android Linter
        run: ./gradlew lint

      - name: Run Ktlint
        run: ./gradlew ktlint

      - name: Run Detekt
        run: ./gradlew detekt

  uploadApk:
    name: Upload Debug Apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Build .APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v1
        with:
          name: improov-debug
          path: ${{ ./app/build/outputs/apk/debug }}
